[terminal]
shell = "/usr/bin/fish"

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
padding = { x = 5, y = 5 }
dynamic_padding = false
opacity = 0.95
startup_mode = "Maximized"

[font]
size = 12.0

[font.bold]
family = "LiterationMono Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "LiterationMono Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "LiterationMono Nerd Font"
style = "Medium Italic"

[font.normal]
family = "LiterationMono Nerd Font"
style = "Medium"

# Default colors
[colors.primary]
background = '#1b1b1b'
foreground = '#ffffff'

[colors.cursor]
text = '#161616' 
cursor = '#78a9ff'

# Normal colors
[colors.normal]
black   = '#161616'
red     = '#ee5396'
green   = '#42be65'
yellow  = '#ff7eb6'
blue    = '#33b1ff'
magenta = '#be95ff'
cyan    = '#3ddbd9'   
white   = '#ffffff'  

# Bright colors
[colors.bright]
black   = '#525252'
red     = '#ee5396'
green   = '#42be65'
yellow  = '#ff7eb6'
blue    = '#33b1ff'
magenta = '#be95ff'
cyan    = '#3ddbd9'   
white   = '#ffffff'  
